### ISSUE TITLE
Locale support for bsdtar

### ISSUE THREAD

**Issue by alexnovak** [bazel-contrib/bazel-lib#966]
The bsdtar supplied with bazel-lib doesn't support unicode in mtree files. 

Bsdtar does seem to support locales, but only when compiled with HAVE_SETLOCALE https://github.com/libarchive/libarchive/blob/40ff837717b89e9a5d2c735758f503d124d17b72/tar/bsdtar.c#L190-L192

In the libarchive compilation that underpins this, it seems like we're configuring this for libarchive, but perhaps it isn't making its way to the bsdtar compilation? https://github.com/bazelbuild/bazel-central-registry/commit/60501022be9ef827027fab268d6ba6809acb0e93#diff-7362d45a2c906ff9c0922ff1f104e88aa28197d9345dabbc18a7a5740f3959e6R1352

Does it also have to depend on `//:config`? I'm not particularly familiar with bazel cc rules.

**Comment by plobsing** [comment]
The [mtree file format](https://man.freebsd.org/cgi/man.cgi?mtree(5)) does not support multi-byte sequences; the contents of an mtree file are expected to be 7-bit ASCII. Content not conforming to that expectation must be represented using escape sequences:

 >      When encoding file or pathnames,	any backslash character	 or  character
 >      outside of the 95 printable ASCII characters must be encoded as a back-
 >      slash  followed	by  three octal	digits.	 When reading mtree files, any
 >      appearance of a backslash followed by three octal digits	should be con-
 >      verted into the corresponding character.

Assuming you want UTF-8[^enc-agnostic], "ő" can be represented as `\305\201` in mtree pathnames.

[^enc-agnostic]: Encoding is not prescribed by mtree or tar, you could use some other encoding if you really wanted to.

**Comment by plobsing** [comment]
FWIW, I am trying to land a [change](https://github.com/bazel-contrib/bazel-lib/pull/985) to make that cleanup automatic if you use the `mtree_spec` rule to create your mtree. That change works using a big pile of `sed`, so if you're managing your own mtree, you could probably re-use / modify some of those scripts.
