### ISSUE TITLE
[FR]: support output groups in copy_file

### ISSUE THREAD

**Issue by joca-bt** [bazel-contrib/bazel-lib#977]
Would it be possible to support output groups in `copy_file`? For example, to copy the tar generated by `oci_load` the user uses a `filegroup` and then a `genrule` (or `copy_file`). If `copy_file` could support output groups then these 2 steps could be merged into 1.

The idea is to replace something like:

```
oci_load(
    name = _oci_load,
    ...
)

native.filegroup(
    name = _filegroup,
    srcs = [
        _oci_load,
    ],
    output_group = "tarball",
)

native.genrule(
    name = name,
    srcs = [
        _filegroup,
    ],
    outs = [
        "{}.tar".format(name),
    ],
    cmd = "cp $< $@",
)
```

with something like:

```
oci_load(
    name = _oci_load,
    ...
)

copy_file(
    name = name,
    src = _oci_load,
    out = "{}.tar".format(name),
    ... # output groups configuration
)
```

**Comment by alexeagle** [comment]
I think this is adding complexity in the wrong spot, we want these to stay minimal so it's possible to maintain the repo. Could you just make a macro in your repo so the BUILD file looks the way you want?
